### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [royce20002006/Rainbow-BnB#1]
# API Docs:
Looks Good! Approved! 

## Tasks:
- [x] Create Routes for API backend
- [x] Add relevant methods
- [x] Attach DB Diagram to .md file

# DB Diagram:
Some small changes to be adjusted. I noticed these on a second glance, but they should be quick fixes. Mostly the fact we have inverse one-to-many associations.

## Tasks: 
- [x] Adjust the relationship between Users and Reviews
- [x] Adjust the relationship between Spots and Reviews

# Deadline:
Please aim to complete the listed tasks by EOD on Monday, May 13th as we are looking to have all documentations approved in order to move on to the next phase of our project life cycle the following day.

**Comment by AnthonyBronca** [comment]
# DB Diagram
- [ ] Consider that hashedPassword is going to be a length of 60, due to the salt we are adding. If we were to create a database with a length of 30 max, we would run into some bugs

# API Docs
Approved

**Comment by AnthonyBronca** [comment]
# DB Diagram

- [ ] price needs to be a decimal
- [ ] make all table names capitalized
